CREATE TABLE Quotes (
	Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	FirstName VARCHAR(50),
	LastName VARCHAR(50),
	EmailAddress VARCHAR(60),
	DateOfBirth VARCHAR(20) NOT NULL,
	CarYear INT NOT NULL,
	CarMake VARCHAR(50) NOT NULL,
	CarModel VARCHAR(50) NOT NULL,
	DUI VARCHAR(10) NOT NULL,
	SpeedingTicket INT NOT NULL,
	Coverage VARCHAR(20) NOT NULL,
	Amount FLOAT NOT NULL
);